import sortBy from 'lodash.sortby'
import { StyleSpecification } from 'maplibre-gl'
import basemap from './basemap'
import { LayerSpecificationWithZIndex } from './types'

const backgroundColour = '#DBE8A5'
const waterColour = '#2EADD9'

const campingColours = {
  camping: '#AFC944',
  vehicles: '#c3c152',
  accessible: '#73d579',
}

const layers: LayerSpecificationWithZIndex[] = [
  {
    id: 'background',
    type: 'background',
    paint: {
      'background-color': backgroundColour,
    },
  },
  ...basemap,
  {
    id: 'bounding_box',
    type: 'fill',
    source: 'site_plan',
    'source-layer': 'bounding_box',
    paint: {
      'fill-color': backgroundColour,
    },
  },
  {
    id: 'slope',
    type: 'raster',
    source: 'slope',
    minzoom: 5,
  },
  {
    id: 'hillshade',
    type: 'raster',
    source: 'hillshade',
    minzoom: 5,
  },
  {
    id: 'ortho',
    type: 'raster',
    source: 'ortho',
    minzoom: 15,
  },
  {
    id: 'background_areas_backstage',
    type: 'fill',
    source: 'site_plan',
    'source-layer': 'areas_backstage',
    paint: {
      'fill-pattern': 'no-access',
    },
  },
  {
    id: 'background_areas_parking',
    type: 'fill',
    source: 'site_plan',
    'source-layer': 'parking',
    paint: {
      'fill-color': '#d6cca0',
    },
  },
  {
    id: 'background_areas_camping_polygon',
    type: 'fill',
    source: 'site_plan',
    'source-layer': 'areas_camping',
    paint: {
      'fill-color': [
        'match',
        ['get', 'type'],
        'vehicles',
        campingColours['vehicles'],
        'accessible',
        campingColours['accessible'],
        campingColours['camping'],
      ],
    },
  },
  {
    id: 'background_areas_camping_outline',
    type: 'line',
    source: 'site_plan',
    'source-layer': 'areas_camping',
    paint: {
      'line-color': 'rgba(10, 100, 10, 0.4)',
      'line-blur': 7,
      'line-width': 3,
    },
  },
  {
    id: 'background_natural_woodland_polygon',
    type: 'fill',
    source: 'site_plan',
    'source-layer': 'natural_woodland_polygon',
    layout: {},
    paint: {
      'fill-color': '#528329',
    },
  },
  {
    id: 'background_natural_hedges_polygon',
    type: 'fill',
    source: 'site_plan',
    'source-layer': 'natural_hedges_polygon',
    layout: {},
    paint: {
      'fill-color': '#528329',
    },
  },
  {
    id: 'background_water_linestring',
    type: 'line',
    source: 'site_plan',
    'source-layer': 'surfacewater_line',
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
      'line-round-limit': 1.1,
    },
    paint: {
      'line-color': waterColour,
      'line-width': ['interpolate', ['linear'], ['zoom'], 13, 1, 15, 2, 18, 6],
    },
  },
  {
    id: 'background_water_polygon',
    type: 'fill',
    source: 'site_plan',
    'source-layer': 'surfacewater_area',
    layout: {},
    paint: {
      'fill-pattern': 'water',
    },
  },
  {
    id: 'background_water_polygon_shadow',
    type: 'line',
    source: 'site_plan',
    'source-layer': 'surfacewater_area',
    layout: {},
    paint: {
      'line-color': '#1D718C',
      'line-width': ['interpolate', ['linear'], ['zoom'], 13, 0, 18, 2],
    },
  },
  {
    id: 'paths_grass',
    type: 'fill',
    source: 'site_plan',
    'source-layer': 'path_area',
    filter: ['==', ['get', 'type'], 'grass'],
    layout: {},
    paint: {
      'fill-color': backgroundColour,
    },
  },
  {
    id: 'paths_tracks_case',
    type: 'line',
    source: 'site_plan',
    'source-layer': 'tracks',
    minzoom: 0,
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
    },
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 12, 0, 17, 5],
      'line-color': 'rgba(132, 131, 131, 1)',
      'line-blur': 0.5,
    },
  },
  {
    id: 'paths_trackway_case',
    type: 'line',
    source: 'site_plan',
    'source-layer': 'path_area',
    filter: ['==', ['get', 'type'], 'trackway'],
    layout: {},
    paint: {
      'line-width': 3,
      'line-color': 'rgba(140, 140, 140, 1)',
    },
  },
  {
    id: 'paths_trackway',
    type: 'fill',
    source: 'site_plan',
    'source-layer': 'path_area',
    filter: ['==', ['get', 'type'], 'trackway'],
    layout: {},
    paint: {
      'fill-color': 'rgba(185, 185, 185, 1)',
    },
  },
  {
    id: 'paths_tracks',
    type: 'fill',
    source: 'site_plan',
    'source-layer': 'tracks',
    minzoom: 0,
    paint: {
      'fill-color': 'rgba(177, 165, 147, 1)',
      'fill-outline-color': 'rgba(98, 98, 97, 0)',
    },
  },
  {
    id: 'heras',
    type: 'line',
    source: 'site_plan',
    'source-layer': 'fence',
    filter: ['==', ['get', 'type'], 'heras'],
    paint: {
      'line-color': 'rgba(148, 63, 63, 1)',
    },
  },
  {
    id: 'ped_barrier',
    type: 'line',
    source: 'site_plan',
    'source-layer': 'fence',
    filter: ['==', ['get', 'type'], 'ped'],
    paint: {
      'line-color': '#286f70',
    },
  },
  {
    id: 'structures_shadow',
    type: 'line',
    source: 'site_plan',
    'source-layer': 'structure_polygon',
    filter: ['==', ['get', 'layer_type'], 'cover'],
    minzoom: 0,
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
    },
    paint: {
      'line-color': 'rgba(0, 0, 0, 0.3)',
      'line-width': 6,
      'line-blur': 3,
    },
  },
  {
    id: 'structures_polygon',
    type: 'fill',
    source: 'site_plan',
    'source-layer': 'structure_polygon',
    filter: ['==', ['get', 'layer_type'], 'cover'],
    minzoom: 0,
    paint: {
      'fill-color': '#F9E200',
    },
  },
  {
    id: 'structures_outline',
    type: 'line',
    source: 'site_plan',
    'source-layer': 'structure_polygon',
    filter: ['==', ['get', 'layer_type'], 'cover'],
    minzoom: 0,
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
    },
    paint: {
      'line-color': 'rgba(90, 81, 31, 1)',
    },
  },
  {
    id: 'structures_structure_linestring',
    type: 'line',
    source: 'site_plan',
    'source-layer': 'structure_linestring',
    filter: ['==', ['get', 'layer_type'], 'structure'],
    minzoom: 0,
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
    },
    paint: {
      'line-color': 'rgba(90, 81, 31, 1)',
    },
  },
  {
    id: 'structures_structure_polygon',
    type: 'line',
    source: 'site_plan',
    'source-layer': 'structure_polygon',
    filter: ['==', ['get', 'layer_type'], 'structure'],
    minzoom: 0,
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
    },
    paint: {
      'line-color': 'rgba(90, 81, 31, 1)',
    },
  },
  {
    id: 'structures_guys',
    type: 'line',
    source: 'site_plan',
    'source-layer': 'structure_linestring',
    filter: ['==', ['get', 'layer_type'], 'guys'],
    minzoom: 0,
    paint: {
      'line-color': 'rgb(153, 144, 93)',
    },
  },
  {
    id: 'structures_exits',
    type: 'line',
    source: 'site_plan',
    'source-layer': 'structures_exits_linestring',
    minzoom: 0,
    paint: {
      'line-width': 3,
      'line-color': 'rgb(153, 144, 93)',
    },
  },
  {
    id: 'walls',
    type: 'line',
    source: 'site_plan',
    'source-layer': 'walls',
  },
  {
    id: 'fences',
    type: 'line',
    source: 'site_plan',
    'source-layer': 'fences_permanent',
    paint: {
      'line-color': 'rgba(134, 134, 101, 1)',
    },
  },
  {
    id: 'buildings',
    type: 'fill-extrusion',
    source: 'basemap',
    'source-layer': 'buildings',
    layout: {},
    paint: {
      'fill-extrusion-color': 'rgba(189, 170, 85, 1)',
      'fill-extrusion-height': 4,
    },
  },
  {
    id: 'services_comms_ducts_case',
    type: 'line',
    source: 'site_plan',
    'source-layer': 'telecom_ducts',
    layout: {},
    paint: {
      'line-color': 'rgba(150, 150, 150, 1)',
      'line-width': 3,
    },
  },
  {
    id: 'services_comms_ducts',
    type: 'line',
    source: 'site_plan',
    'source-layer': 'telecom_ducts',
    layout: {},
    paint: {
      'line-color': 'rgba(187, 0, 218, 1)',
      'line-width': 2,
    },
  },
  {
    id: 'services_comms_manholes',
    type: 'circle',
    source: 'site_plan',
    'source-layer': 'telecom_manholes',
    minzoom: 15,
    paint: {
      'circle-color': 'rgba(187, 0, 218, 1)',
      'circle-stroke-width': 1,
    },
  },
  {
    id: 'services_comms_manholes_label',
    type: 'symbol',
    source: 'site_plan',
    'source-layer': 'telecom_manholes',
    minzoom: 15,
    layout: {
      'text-field': '{ref}',
      'text-font': ['Open Sans Regular'],
      'text-size': 14,
      'text-offset': [-1, 0],
    },
    paint: {
      'text-halo-color': 'rgba(255, 255, 255, 1)',
      'text-halo-width': 2,
    },
  },
  {
    id: 'services_water_lines',
    type: 'line',
    source: 'site_plan',
    'source-layer': 'water_lines',
    layout: {},
    paint: {
      'line-color': '#00C5FF',
      'line-width': 2,
    },
  },
  {
    id: 'services_water_points',
    type: 'circle',
    source: 'site_plan',
    'source-layer': 'water_points',
    paint: {
      'circle-color': 'rgba(0, 197, 255, 1)',
      'circle-stroke-color': 'rgba(22, 0, 195, 1)',
      'circle-stroke-width': 2,
      'circle-radius': 3,
    },
  },
  {
    id: 'boundary',
    type: 'line',
    source: 'site_plan',
    'source-layer': 'boundary',
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
    },
    paint: {
      'line-color': 'rgba(226, 11, 11, 1)',
      'line-dasharray': [10, 3],
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1, 17, 2],
    },
  },
  {
    id: 'lighting_festoon',
    type: 'line',
    source: 'site_plan',
    'source-layer': 'lighting_festoon',
    layout: {},
    paint: {
      'line-color': 'rgba(200, 184, 42, 1)',
      'line-width': 2,
    },
  },
  {
    id: 'lighting_festoon_labels',
    type: 'symbol',
    source: 'site_plan',
    'source-layer': 'lighting_festoon',
    minzoom: 19,
    maxzoom: 24,
    layout: {
      'symbol-placement': 'line',
      'text-field': 'Festoon ({length}m)',
      'text-size': 12,
      'text-optional': false,
      'text-font': ['Open Sans Regular'],
      'text-keep-upright': true,
      'text-allow-overlap': false,
      'text-offset': [0, -1],
    },
    paint: {
      'text-halo-color': 'rgba(241, 241, 241, 0.8)',
      'text-halo-width': 3,
      'text-color': 'rgba(200, 184, 42, 1)',
    },
  },
  {
    id: 'background_trees',
    type: 'symbol',
    source: 'site_plan',
    'source-layer': 'trees',
    minzoom: 13,
    layout: {
      'icon-image': 'tree',
      'icon-size': [
        'interpolate',
        ['exponential', 1.5],
        ['zoom'],
        14,
        0.01,
        22,
        ['*', ['to-number', ['coalesce', ['get', 'crown_diameter'], 5]], 0.1],
      ],
      'icon-allow-overlap': true,
      'icon-rotate': ['%', ['*', ['get', 'gid'], 200], 360],
    },
    paint: {},
  },
  /*
    {
        id: 'noc_datenklo',
        type: 'symbol',
        source: 'noc',
        filter: ['get', 'dk'],
        minzoom: 16,
        layout: {
            'icon-image': [
                'case',
                ['get', 'alive'],
                'datenklo_active',
                ['all', ['get', 'active'], ['!', ['get', 'alive']]],
                'datenklo_down',
                'datenklo',
            ],
            'icon-size': ['interpolate', ['linear'], ['zoom'], 16, 0.1, 24, 2],
            'icon-allow-overlap': true,
            'text-field': '{name}',
            'text-size': 12,
            'text-optional': false,
            'text-font': ['Open Sans Regular'],
            'text-keep-upright': true,
            'text-allow-overlap': true,
            'text-offset': [
                'interpolate',
                ['linear'],
                ['zoom'],
                17,
                ['literal', [0, 2]],
                24,
                ['literal', [0, 6]],
            ],
        },
        paint: {
            'text-halo-color': 'rgba(241, 241, 241, 0.8)',
            'text-halo-width': 3,
            'text-opacity': ['interpolate', ['linear'], ['zoom'], 16.9, 0, 17, 1],
        },
    },
    {
        id: 'noc_switch',
        type: 'circle',
        source: 'noc',
        filter: ['!', ['get', 'dk']],
        minzoom: 16,
        layout: {},
        paint: {
            'circle-color': [
                'case',
                ['get', 'alive'],
                'rgba(20, 255, 20, 1)',
                ['all', ['get', 'active'], ['!', ['get', 'alive']]],
                'rgba(255, 20, 20, 1)',
                'rgba(170, 170, 170, 1)',
            ],
            'circle-stroke-color': 'rgba(75, 0, 130, 1)',
            'circle-stroke-width': 2,
            'circle-radius': ['interpolate', ['linear'], ['zoom'], 16, 3, 24, 15],
        },
    },
    {
        id: 'noc_switch_label',
        type: 'symbol',
        source: 'noc',
        filter: ['!', ['get', 'dk']],
        minzoom: 19,
        layout: {
            'text-field': '{name}',
            'text-font': ['Open Sans Regular'],
            'text-size': 12,
            'text-optional': false,
            'text-offset': [0, 1],
        },
        paint: {
            'text-halo-color': 'rgba(255, 255, 255, 1)',
            'text-halo-width': 2,
        },
        },*/
  {
    id: 'labels_camping',
    type: 'symbol',
    source: 'site_plan',
    'source-layer': 'camping_centroid',
    minzoom: 16,
    maxzoom: 24,
    layout: {
      'text-field': 'Camping: {camping}',
      'text-font': ['Open Sans Regular'],
      'text-justify': 'center',
      'text-size': ['interpolate', ['linear'], ['zoom'], 16, 10, 24, 24],
      'text-padding': 2,
      'symbol-placement': 'point',
      'symbol-spacing': 1000,
      'symbol-avoid-edges': true,
      'text-max-width': 8,
    },
    paint: {
      'text-halo-width': 3,
      'text-halo-blur': 4,
      'text-halo-color': 'rgba(241, 241, 241, 1)',
    },
  },
  {
    id: 'labels_gate',
    type: 'symbol',
    source: 'site_plan',
    'source-layer': 'labels_gate_labels_point',
    minzoom: 16,
    maxzoom: 24,
    layout: {
      'text-field': '{text}',
      'text-size': 12,
      'text-optional': false,
      'text-font': ['Open Sans Regular'],
      'text-keep-upright': true,
      'text-ignore-placement': false,
      'text-allow-overlap': false,
    },
    paint: {
      'text-halo-color': 'rgba(241, 241, 241, 1)',
      'text-halo-width': 3,
      'text-halo-blur': 4,
      'text-color': 'rgba(0, 0, 0, 1)',
    },
  },
  {
    id: 'labels_streets',
    type: 'symbol',
    source: 'site_plan',
    'source-layer': 'street_names',
    minzoom: 16,
    layout: {
      'text-field': '{name}',
      'text-font': ['Raleway SemiBold'],
      'text-size': ['interpolate', ['linear'], ['zoom'], 16, 8, 17, 9, 23, 50],
      'text-max-angle': 10,
      'symbol-placement': 'line',
      'symbol-spacing': 500,
    },
    paint: {
      'text-halo-color': 'rgba(120, 120, 120, 1)',
      'text-halo-width': 15,
      'text-halo-blur': 40,
      'text-color': 'rgba(250, 250, 250, 1)',
    },
  },
  {
    id: 'labels_structures_5',
    type: 'symbol',
    source: 'site_plan',
    'source-layer': 'structure_centroid',
    filter: ['==', ['get', 'importance'], 5],
    minzoom: 16,
    layout: {
      'text-field': '{name}',
      'text-font': ['Raleway SemiBold'],
      'text-size': ['interpolate', ['linear'], ['zoom'], 16, 8, 17, 9, 23, 50],
      'text-max-angle': 10,
    },
    paint: {
      'text-halo-color': 'rgba(120, 120, 120, 1)',
      'text-halo-width': 15,
      'text-halo-blur': 40,
      'text-color': 'rgba(250, 250, 250, 1)',
    },
  },
  {
    id: 'labels_structures_4',
    type: 'symbol',
    source: 'site_plan',
    'source-layer': 'structure_centroid',
    filter: ['==', ['get', 'importance'], 4],
    minzoom: 17,
    layout: {
      'text-field': '{name}',
      'text-font': ['Raleway SemiBold'],
      'text-size': ['interpolate', ['linear'], ['zoom'], 17, 8, 23, 40],
      'text-max-angle': 10,
    },
    paint: {
      'text-halo-color': 'rgba(120, 120, 120, 1)',
      'text-halo-width': 15,
      'text-halo-blur': 40,
      'text-color': 'rgba(250, 250, 250, 1)',
    },
  },
  {
    id: 'labels_structures_3',
    type: 'symbol',
    source: 'site_plan',
    'source-layer': 'structure_centroid',
    filter: ['==', ['get', 'importance'], 3],
    minzoom: 18,
    layout: {
      'text-field': '{name}',
      'text-font': ['Raleway SemiBold'],
      'text-size': ['interpolate', ['linear'], ['zoom'], 18, 8, 23, 30],
      'text-max-angle': 10,
    },
    paint: {
      'text-halo-color': 'rgba(120, 120, 120, 1)',
      'text-halo-width': 15,
      'text-halo-blur': 40,
      'text-color': 'rgba(250, 250, 250, 1)',
    },
  },
  {
    id: 'labels_structures_2',
    type: 'symbol',
    source: 'site_plan',
    'source-layer': 'structure_centroid',
    filter: ['==', ['get', 'importance'], 2],
    minzoom: 19,
    layout: {
      'text-field': '{name}',
      'text-font': ['Raleway SemiBold'],
      'text-size': ['interpolate', ['linear'], ['zoom'], 19, 8, 23, 25],
      'text-max-angle': 10,
    },
    paint: {
      'text-halo-color': 'rgba(120, 120, 120, 1)',
      'text-halo-width': 15,
      'text-halo-blur': 40,
      'text-color': 'rgba(250, 250, 250, 1)',
    },
  },
  {
    id: 'labels_areas',
    type: 'symbol',
    source: 'site_plan',
    'source-layer': 'areas_event',
    minzoom: 15,
    layout: {
      'text-field': '{name}',
      'text-font': ['Raleway SemiBold'],
      'text-size': ['interpolate', ['linear'], ['zoom'], 15, 9, 23, 40],
      'text-max-angle': 10,
    },
    paint: {
      'text-halo-color': 'rgba(120, 120, 120, 1)',
      'text-halo-width': 15,
      'text-halo-blur': 40,
      'text-color': 'rgba(250, 250, 250, 1)',
    },
  },
]

const style: StyleSpecification = {
  version: 8,
  name: 'EMF',
  center: [-2.3784, 52.0411],
  zoom: 16,
  bearing: 0,
  pitch: 0,
  sources: {
    basemap: {
      type: 'vector',
      tiles: ['https://map.emfcamp.org/tiles/basemap/{z}/{x}/{y}'],
      maxzoom: 14,
      attribution: '© OpenStreetMap contributors',
    },
    site_plan: {
      type: 'vector',
      tiles: ['https://map.emfcamp.org/tiles/_main/{z}/{x}/{y}'],
    },
    villages: {
      type: 'geojson',
      data: 'https://www.emfcamp.org/api/villages.geojson',
    },
    slope: {
      type: 'raster',
      tiles: ['https://map.emfcamp.org/tiles/slope/{z}/{x}/{y}'],
      tileSize: 256,
      attribution: 'Elevation data © Environment Agency 2022. All rights reserved.',
    },
    hillshade: {
      type: 'raster',
      tiles: ['https://map.emfcamp.org/tiles/hillshade/{z}/{x}/{y}'],
      tileSize: 256,
      attribution: 'Elevation data © Environment Agency 2022. All rights reserved.',
    },
    ortho: {
      type: 'raster',
      tileSize: 256,
      tiles: ['https://map.emfcamp.org/tiles/ortho/{z}/{x}/{y}'],
    },
    vehicles: {
      type: 'geojson',
      data: { type: 'FeatureCollection', features: [] },
    },
  },
  sprite: 'https://openmaptiles.github.io/positron-gl-style/sprite',
  glyphs: 'https://map.emfcamp.org/tiles/font/{fontstack}/{range}',
  layers: sortBy(layers, [(item) => item.zindex || 0]).map((item) => {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { zindex: _, ...new_item } = item
    return new_item
  }),
}

export default style
